version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=https://learning-wildcat-becoming.ngrok-free.app
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'

networks:
  app-network:
    driver: bridge
